name: release

on:
    push:
      tags:
        - 'v*.*.*' # Indicates that it is triggered when a new Release is created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # A default variable that allows adding files to Release
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23
          binary_name: "shinner-bot"
          extra_files: README.md
          project_path: "./cmd/bot"
